#!/bin/bash

read -p "Provide the location of the Red Hat Satellite DB tarball : " LOC

echo `file $LOC` | grep gzip >/dev/null 2>&1
result=`echo $?`

if [ $result -ne 0 ]; then
  echo "File not found or the tarball is not in intended format"
  exit 1
else
  echo -e "\nExtracting the tarball\n"
  mkdir /tmp/backup-`date +%Y-%m-%d`
  tar -xvzf $LOC -C /tmp/backup-`date +%Y-%m-%d` >/dev/null 2>&1
  # Drop the existing Red Hat Satellite PostgreSQL databases if any exist.
  echo -e "This will drop the existing Foreman and Candlepin databases\n"
  read -p "Do you want to continue [Y/N] : " ans
 
  if [ $ans == 'Y' ] || [ $ans == 'y' ]; then
     katello-service stop >/dev/null 2>&1
     service postgresql stop >/dev/null 2>&1
     service tomcat stop >/dev/null 2>&1
     service postgresql start >/dev/null 2>&1
     echo -e "\nDropping foreman and candlepin databases" 
     runuser - postgres -c "dropdb foreman"
     runuser - postgres -c "dropdb candlepin"

     # Restore Red Hat Satellite PostgreSQL databases from the dump
     echo -e "\n\nRestoring databases foreman and candlepin from the dump" 
     runuser - postgres -c "pg_restore -C -d postgres /tmp/backup-`date +%Y-%m-%d`/foreman.dump" >/dev/null 2>&1
     runuser - postgres -c "pg_restore -C -d postgres /tmp/backup-`date +%Y-%m-%d`/candlepin.dump" >/dev/null 2>&1

     # Ensure MongoDB is running and delete the old data.
     echo -e "\nStart the MongoDB database and clear old data"
     service mongod start >/dev/null 2>&1
     echo 'db.dropDatabase();' | mongo pulp_database >/dev/null 2>&1

     mongorestore --host localhost /tmp/backup-`date +%Y-%m-%d`/mongo_dump/pulp_database/ >/dev/null 2>&1

     # Restart all Red Hat Satellite processes.
     echo -e "\nRestarting all services"
     service postgresql start >/dev/null 2>&1
     service tomcat start >/dev/null 2>&1
     katello-service start >/dev/null 2>&1

     echo -e "\nClearing unwanted data" 
     rm -rf /tmp/filelist
     rm -rf /tmp/backup-`date +%Y-%m-%d`
  else
     echo -e "\nExiting without any changes"
     exit 1
  fi
fi
